enum {
    COHVAR_BINDS = 1,
    COHVAR_CAMERA,
    COHVAR_CAM_IS_DETACHED,
    COHVAR_CONTROLS_FROM_SERVER,
    COHVAR_ENT_CHAR_OFFSET,
    COHVAR_ENT_NEXT_MOV_OFFSET,
    COHVAR_ENT_SERVERID_OFFSET,
    COHVAR_ENTTBL,
    COHVAR_GAME_TIME,
    COHVAR_NOCOLL,
    COHVAR_PLAYER_ENT,
    COHVAR_PLAYER_KBOFFSET,
    COHVAR_SEEALL,
    COHVAR_START_CHOICE,
    COHVAR_TARGET,
    COHFUNC_ANNOYING_ALERT,
    COHFUNC_CALLOC,
    COHFUNC_COPY_ATTRIBS,
    COHFUNC_DETACH_CAMERA,
    COHFUNC_DIALOG,
    COHFUNC_DIALOG_GET_TEXT,
    COHFUNC_ENT_TELEPORT,
    COHFUNC_INIT_KEYBINDS,
    COHFUNC_LOAD_MAP_DEMO,
    COHFUNC_MAP_CLEAR,
    COHFUNC_MOV_BY_NAME,
    COH_END
};

void InitCoh(int vers);
unsigned long CohAddr(int id);

void PatchI24();
void PatchI23();
